  
# Branches that trigger a build on commit
trigger:
- main
- feature/*

variables:
  - name: Codeql.Enabled
    value: true

# Branches that trigger builds on PR
pr:
- master
- main
- feature/*

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  variables:
    _os: Windows
  strategy:
    maxParallel: 4
    matrix:
      Debug:
        _configuration: Debug
      Release:
        _configuration: Release
  steps:
    - script: eng\common\CIBuild.cmd -configuration $(_configuration) -prepareMachine
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\log\$(_configuration)'
        ArtifactName: '$(_configuration) log folder'
        publishLocation: Container
      continueOnError: true
      condition: failed()
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\bin'
        ArtifactName: '$(_configuration) bin folder'
        publishLocation: Container
      continueOnError: true
      condition: failed()
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\VSSetup\$(_configuration)'
        ArtifactName: '$(_configuration) VSSetup folder'
        publishLocation: Container
      continueOnError: true
      condition: failed()
